# TODO: This updates global state (shared by all CI jobs) and doesn't do synchronization or proper cleanup
.git-access:
  before_script:
    - git config --global credential.helper store
    - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@gl1.dcdpr.com" > ~/.git-credentials
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gl1.dcdpr.com".insteadOf ssh://git@gl1.dcdpr.com
  after_script:
    - git config --global --unset url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gl1.dcdpr.com".insteadOf

rustup-update:
  stage: .pre
  needs: []
  tags:
    - shell-executor
  script:
    - rustc --version
    - rustup update
    - rustc --version

cargo-check:
  extends: .git-access
  stage: build
  needs: []
  tags:
    - shell-executor
  script:
    - cargo check --workspace --benches --examples --tests --all-features

cargo-check:release:
  extends: .git-access
  stage: build
  needs: []
  tags:
    - shell-executor
  script:
    - cargo check --workspace --benches --examples --tests --all-features --release

cargo-deny:
  extends: .git-access
  stage: build
  needs: []
  tags:
    - shell-executor
  script:
    - cargo install --locked cargo-deny --version 0.16.2
    - cargo deny --locked --workspace check all

cargo-fmt:
  extends: .git-access
  stage: build
  needs: ["cargo-check", "cargo-check:release", "cargo-deny"]
  tags:
    - shell-executor
  script:
    - cargo fmt --all -- --check

cargo-doc:
  extends: .git-access
  stage: build
  needs: ["cargo-check", "cargo-check:release", "cargo-deny"]
  tags:
    - shell-executor
  variables:
    RUSTDOCFLAGS: "-D warnings"
  script:
    - cargo doc --workspace --no-deps

cargo-clippy:
  extends: .git-access
  stage: build
  needs: ["cargo-check", "cargo-check:release", "cargo-deny"]
  tags:
    - shell-executor
  script:
    - cargo clippy --all --tests -- -D warnings

cargo-test:
  extends: .git-access
  stage: test
  tags:
    - shell-executor
  script:
    - cargo test --workspace

cargo-test:release:
  extends: .git-access
  stage: test
  tags:
    - shell-executor
  script:
    - cargo test --workspace --release
