[workspace]
resolver = "2"
members = [
    "did-btc1-core",
    "did-btc1-crypto",
    "did-btc1-identifier",
    "did-btc1-beacons",
    "did-btc1-bitcoin",
    "did-btc1-resolver",
    "did-btc1",
    "did-btc1-cli",
    "did-btc1-examples",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "git@gl1.dcdpr.com:dcd/did-btc1-rust.git"
authors = ["Dan Pape <dpape@dpape.com>"]

[workspace.dependencies]
# Shared dependencies across all crates
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
onlyerror = "0.1"
tokio = { version = "1.0", features = ["full"] }
url = { version = "2", features = ["serde"] }

# Cryptography
secp256k1 = { version = "0.30", features = ["serde", "rand"] }
sha2 = "0.10"
multibase = "0.9"

# Bitcoin
bitcoin = "0.32"

# JSON processing
serde_jcs = "0.1"

# Internal workspace crates
did-btc1-core = { path = "./did-btc1-core" }
did-btc1-crypto = { path = "./did-btc1-crypto" }
did-btc1-identifier = { path = "./did-btc1-identifier" }
did-btc1-beacons = { path = "./did-btc1-beacons" }
did-btc1-bitcoin = { path = "./did-btc1-bitcoin" }
did-btc1-resolver = { path = "./did-btc1-resolver" }
