[package]
name = "smt-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2"
hex = "0.4"
monotree = { version = "0.4", features = ["db_rocksdb", "db_sled"] }
onlyerror = "0.1"
plotters = "0.3"
rand = "0.8"
rusqlite = { version = "0.37", features = ["bundled"] }
sha2 = "0.10"
