[package]
name = "did-btc1-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
did-btc1-crypto.workspace = true
did-btc1-encoding.workspace = true
onlyerror.workspace = true
serde_json.workspace = true
